# Generated by Django 4.2.4 on 2023-12-14 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0019_remove_bookvotes_upvoted_by"),
        ("authentication", "0007_userprofile_books_userprofile_history_books_and_more"),
        ("upvote_book", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UpvotedbyUsersFlutter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="book.book"
                    ),
                ),
                ("users", models.ManyToManyField(to="authentication.userprofile")),
            ],
        ),
        migrations.CreateModel(
            name="MyUpvoteListFlutter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reasoning", models.TextField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "books",
                    models.ManyToManyField(
                        related_name="upvoted_books", to="book.book"
                    ),
                ),
                (
                    "me",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authentication.userprofile",
                    ),
                ),
            ],
        ),
    ]
