# Generated by Django 4.2.4 on 2023-12-15 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0019_remove_bookvotes_upvoted_by"),
        ("authentication", "0007_userprofile_books_userprofile_history_books_and_more"),
        ("upvote_book", "0002_upvotedbyusersflutter_myupvotelistflutter"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="book.book"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authentication.userprofile",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(model_name="upvotedbyusersflutter", name="book",),
        migrations.RemoveField(model_name="upvotedbyusersflutter", name="users",),
        migrations.DeleteModel(name="MyUpvoteListFlutter",),
        migrations.DeleteModel(name="UpvotedbyUsersFlutter",),
    ]
