# Generated by Django 5.0 on 2023-12-18 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_userprofile_books_userprofile_history_books_and_more'),
        ('reading_history', '0002_alter_readinghistory_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readinghistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.userprofile'),
        ),
    ]
