# Generated by Django 4.2.6 on 2023-10-26 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20231026_1738'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='books',
            field=models.ManyToManyField(to='book.book'),
        ),
    ]
