# Generated by Django 4.2.4 on 2023-10-29 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_book_last_page'),
        ('authentication', '0003_userprofile_upvoted_books_userprofile_wishlist_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='history_books',
            field=models.ManyToManyField(blank=True, related_name='histories', to='book.book'),
        ),
    ]
