# Generated by Django 4.2.6 on 2023-10-29 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_userprofile_upvoted_books_userprofile_wishlist_books'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_user',
        ),
    ]
