# Generated by Django 4.2.6 on 2023-10-29 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_remove_userprofile_is_user'),
        ('authentication', '0004_userprofile_history_books'),
    ]

    operations = [
    ]
