# Generated by Django 4.2.4 on 2023-12-12 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0005_merge_20231030_0005"),
    ]

    operations = [
        migrations.RemoveField(model_name="userprofile", name="books",),
        migrations.RemoveField(model_name="userprofile", name="history_books",),
        migrations.RemoveField(model_name="userprofile", name="is_admin",),
        migrations.RemoveField(model_name="userprofile", name="upvoted_books",),
        migrations.RemoveField(model_name="userprofile", name="wishlist_books",),
    ]
