# Generated by Django 4.2.4 on 2023-12-12 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0017_remove_bookvotes_upvoted_by"),
        ("authentication", "0006_remove_userprofile_books_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="books",
            field=models.ManyToManyField(to="book.book"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="history_books",
            field=models.ManyToManyField(
                blank=True, related_name="histories", to="book.book"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="is_admin",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="upvoted_books",
            field=models.ManyToManyField(
                blank=True, related_name="upvoters", to="book.book"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="wishlist_books",
            field=models.ManyToManyField(
                blank=True, related_name="wishlists", to="book.book"
            ),
        ),
    ]
