# Generated by Django 4.2.4 on 2023-10-29 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_book_total_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='last_page',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
