# Generated by Django 4.2.4 on 2023-10-29 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_book_last_page'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='last_page',
            new_name='progress',
        ),
    ]
