# Generated by Django 4.2.4 on 2023-11-25 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_rename_last_page_book_progress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='progress',
        ),
        migrations.RemoveField(
            model_name='book',
            name='total_votes',
        ),
        migrations.RemoveField(
            model_name='book',
            name='total_wishlist',
        ),
    ]
