# Generated by Django 4.2.4 on 2023-11-25 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_remove_book_progress_remove_book_total_votes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='progress',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='total_votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='total_wishlist',
            field=models.IntegerField(default=0),
        ),
    ]
