# Generated by Django 4.2.4 on 2023-11-27 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_book_progress_book_total_votes_book_total_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='progress',
        ),
        migrations.RemoveField(
            model_name='book',
            name='total_votes',
        ),
        migrations.RemoveField(
            model_name='book',
            name='total_wishlist',
        ),
    ]
