# Generated by Django 4.2.4 on 2023-11-29 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0011_rename_progress_book_last_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='last_page',
        ),
    ]
