# Generated by Django 4.2.4 on 2023-12-06 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0013_remove_book_total_votes_remove_book_total_wishlist_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="wishlist", name="book",),
        migrations.DeleteModel(name="Votes",),
        migrations.DeleteModel(name="Wishlist",),
    ]
