# Generated by Django 4.2.4 on 2023-12-06 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0014_remove_wishlist_book_delete_votes_delete_wishlist"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookWishlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_wishlist", models.IntegerField(default=0)),
                (
                    "book",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wishlist",
                        to="book.book",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BookVotes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_votes", models.IntegerField(default=0)),
                (
                    "book",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="book.book",
                    ),
                ),
            ],
        ),
    ]
