# Generated by Django 4.2.4 on 2023-12-12 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0006_remove_userprofile_books_and_more"),
        ("book", "0015_bookwishlist_bookvotes"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookvotes",
            name="upvoted_by",
            field=models.ManyToManyField(
                blank="true", related_name="users", to="authentication.userprofile"
            ),
        ),
    ]
